### ISSUE TITLE
You can add UIViewControllerRepresentable method to load UIKit ViewControllers on TabBar items.

### ISSUE THREAD

**Issue by SevioCorrea** [fahadshafiq48/EasyCustomTabBar#1]
I performed some tests with your Framework and it was possible to use the UIViewControllerRepresentable method to load UIKit Views in the TabBar items.
It would be great if you added it so that we don't have to rewrite the code several times.

struct MySwiftUIView: UIViewControllerRepresentable {
   func makeUIViewController(context: Context) -> UIKitViewController {
     return UIKitViewController()
}
func updateUIViewController(_ uiViewController: UIKitViewController, context: Context) {
}

This can be a big help.

**Comment by fahadshafiq48** [comment]
Unfortunately, what you have suggested is not in the scope of this library. But you can use generics to reuse code and pass your UIKit file's name as a generic param.
