### ISSUE TITLE
Center Button Style

### ISSUE THREAD

**Issue by foya10** [fahadshafiq48/EasyCustomTabBar#2]
Hi,

I working with the EazyCustomTabBar, first... is a very very very nice resource, i am grateful for your work

So, I have a problem with the performance of center button... this button not work lika a tabItem in the TabView, maybe it is created like this.

So, exists this alternative. ?

**Comment by fahadshafiq48** [comment]
Thanks for using EasyCustomTabBar. This pod is made to give customization in your hand. You can use the center button just like other tab bar items. In the example project, the view on the center button has transparency just to show an alternative way of presenting views.

You can write your own code on the center button action. It will work smoothly. This library doesn't perform any task that could compromise performance on a single-button action (In this case center button action).

if centreBtnPressed == true { 
 // write your code here
}

If you have any other queries then you can write them here. I would love to hear back from you. Thanks!

**Comment by fahadshafiq48** [comment]
Since this is not an issue or bug and I haven't heard back from you or anybody else about this. I am closing this for now.

**Comment by AmrSaleh07** [comment]
Hi Fahad,
thank you for this great pod, but I'm facing the same issue If I press on center button I can't navigate to another bar items unless I press on centered button again.
can you show me example for implementing it like normal behavior.

Thanks in advance.

**Comment by fahadshafiq48** [comment]
Hi @AmrSaleh07,
i have fixed the issue in the v1.0.2 please check it out.
Thanks for pointing out..!
